server:
  port: ${PORT:8080}

spring:
  application:
    name: robotest-server
  lifecycle:
    timeout-per-shutdown-phase: 60s
  threads:
    virtual:
      enabled: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  config:
    import: optional:classpath:.env[.properties]
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      write-durations-as-timestamps: true
      fail-on-empty-beans: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/robotest}
    username: ${DATASOURCE_USERNAME:robotest}
    password: ${DATASOURCE_PASSWORD:robotest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      user: default
      password: ${REDIS_PASSWORD:}
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

#################### 框架相关配置 ####################

migoo:
  debug: ${DEBUG_STATUS:false}
  xss:
    enable: true
  security:
    authorization:
      access-token-expires: 24H
      secret-key: ${JWT_SECRET_KEY:9aef92670f10242388d55d2ffc0eeb43}
    password-secret: ${PASSWORD_SECRET:17c553e34228909b1f8cef6d1de0b53d}
    logout-url: /logout
    permit-all-urls:
      - /api/workspace/invitations/verify
      - /api/workspace/invitations/join
      - /debug/**

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: false
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  mapper-locations: classpath*:mapper/*.xml
